name: Milkleaks
subname: Блог
description: Блог о компьютерных играх, фильмах, книгах, вебе и всем прочем.
author: Александра Травкина

url: http://milkleaks.ru
baseurl:
permalink: /blog/:title/
disqus: milkleaks-ru
image: /assets/images/cat.png

version: v3.5.2
safe: false

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  
# Tags and categories
tag_permalink_style: pretty
tag_page_layout: tag
tag_page_dir: tag
tag_page_data:
  sitemap: false

## Collections

## Plugins
plugins:
  - octopress-paginate
  - jekyll-redirect-from
  - jekyll-auto-image
  - jekyll-sitemap
  - jekyll-feed

# Config for sitemap_generator.rb
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
  
jekyll-press:
  exclude:
    - "feed.xml"
    - "sitemap.xml"
  js_options: {}
  css_options: {}
  html_options: {}