title: Блог Александры Травкиной
email: mrs.cuteshy@gmail.com
description: Блог о веб-дизайне, компьютерах и компьютерных играх
author: Александра Травкина
url: https://fixel.ru
permalink: /blog/:title/
baseurl:

# Jekyll
safe: false

# Socail
github: sashatravkina
twitter: sasha_travkina
telegram: sashatravkina

# Deafults layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
plugins:
  - jekyll-include-cache
  - jekyll-auto-image
  - jekyll-typogrify
  - jekyll-paginate
  - jekyll-archives
  - jekyll-extlinks
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Extlinks
extlinks:
  attributes: {rel: nofollow, target: _blank} 
  rel_exclude: ['fixel.ru']

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: '/page-:num/'
  title: ':title'
  sort_reverse: true

# Archives
jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive
  permalinks:
    year: "/blog/:year/"
    month: "/blog/:year/:month/"
    day: "/blog/:year/:month/:day/"
    tag: "/blog/tags/:name/"
    category: "/blog/categories/:name/"

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/turbo.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"