name: Milkleaks
description: Блог о компьютерных играх, фильмах, книгах, вебе и всем прочем.
author: Александра Травкина

# Base
url: https://milkleaks.ru
baseurl:
permalink: /blog/:title/
markdown: kramdown
disqus: milkleaks-ru
image:

# Socail
github: sasha-travkina
twitter: sasha_travkina
telegram: sashatravkina

# Cloudinary
cloudinary: milkleaks
cloudinary-size: c_limit,w_780
cloudinary-big: w_1440

# Jekyll
safe: false

# Navigation
navigation:
  - title: Все записи
    url: /blog/all/
  - title: Фотографии
    url: /photo/
  - title: Об авторе
    url: /about/
  - title: Поддержать
    url: /donate/
  - title: Магазин игр
    url: http://steambuy.com/partner/milkleaks

# Deafults layout
defaults:
  - scope:
      path: ""
      type: photos
    values:
      layout: photo
  - scope:
      path: ""
      type: works
    values:
      layout: work
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Collections     
collections:
  photos:
    output: true
    permalink: /photo/:title/
  works:
    output: true
    permalink: /work/:title/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules/

## Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-auto-image
  - jekyll-typogrify
  - jekyll-paginate
  - jekyll-archives
  - jekyll-extlinks
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-maps
  - jekyll-less

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed

less:
  entrypoint: "static/style.less"
  less_dir: static

# Google maps
maps:
  google:
    api_key: AIzaSyCdzBPyxAeuk-0bG2pyMbO8d32PMBKgcRo

# Extlinks
extlinks:
  attributes: {rel: nofollow, target: _blank} 
  rel_exclude: ['milkleaks.ru']
  
# Pagination
paginate: 8
paginate_path: "/page-:num/"

# Archives
jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive
  permalinks:
    year: "/blog/:year/"
    month: "/blog/:year/:month/"
    day: "/blog/:year/:month/:day/"
    tag: "/blog/tags/:name/"
    category: "/blog/categories/:name/"

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/turbo.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"