name: Milkleaks
description: Блог о компьютерных играх, фильмах, книгах, вебе и всем прочем.
author: Александра Травкина
disqus: milkleaks-ru

url: http://milkleaks.ru
baseurl:
permalink: /blog/:title/

logo-black: /assets/images/logo-black.png
logo-white: /assets/images/logo-white.png
image: /assets/images/cat.png

version: v3.5.2
safe: false

navigation:
  - title: Блог
    url: /blog/
  - title: Об авторе
    url: /about/

defaults:
  - scope:
      path: ""
      type: photos
    values:
      layout: image
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      
collections:
  photos:
    output: true
    permalink: /photo/:year/:month/:day/:slug/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  
## Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-auto-image
  - jekyll-postfiles
  - jekyll-sitemap
  - jekyll-feed
  
pagination:
  enabled: true
  per_page: 8
  permalink: "/page-:num/"
  title: ":title"
  sort_reverse: true
  limit: 0
  
autopages:
  enabled: true
  categories:
    layouts: 
      - "category.html"
    permalink: "/category/:cat/"
    title: "Записи в категории :cat"
  tags:
    layouts: 
      - "tag.html"
    permalink: "/tag/:tag/"
    title: "Записи с тегом #:tag"
  collections: ""

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
  
jekyll-press:
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/sitemap.xml"
  js_options: {}
  css_options: {}
  html_options: {}