name: Milkleaks
description: Блог о компьютерных играх, фильмах, книгах, вебе и всем прочем.
author: Александра Травкина
disqus: milkleaks-ru

url: http://milkleaks.ru
baseurl:
permalink: /blog/:title/

image: /assets/images/cat.png

version: v3.6.2
safe: false

navigation:
  - title: Блог
    url: /blog/
  - title: Об авторе
    url: /about/

defaults:
  - scope:
      path: ""
      type: photos
    values:
      layout: image
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      
collections:
  photos:
    output: true
    permalink: /photo/:year/:month/:day/:slug/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  
## Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-auto-image
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  
paginate: 8
paginate_path: "/page-:num/"

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
  
jekyll-press:
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/sitemap.xml"
  js_options: {}
  css_options: {}
  html_options: {}