name: Milkleaks
description: Блог о компьютерных играх, фильмах, книгах, вебе и всем прочем.
author: Александра Травкина

url: https://milkleaks.ru
baseurl:
permalink: /blog/:title/

image:

version: v3.7.0
safe: false

navigation:
  - title: Блог
    url: /blog/
  - title: Об авторе
    url: /about/

defaults:
  - scope:
      path: ""
      type: photos
    values:
      layout: photo
  - scope:
      path: ""
      type: works
    values:
      layout: work
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      
collections:
  photos:
    output: true
    permalink: /photo/:title/
  works:
    output: true
    permalink: /work/:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .asset-cache
  - .jekyll-cache
  - .DS_Store
  
## Plugins
plugins:
  - font-awesome-sass
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-auto-image
  - jekyll-typogrify
  - jekyll-paginate
  - jekyll-archives
  - jekyll-extlinks
  - jekyll-sitemap
  - jekyll-timeago
  - jekyll-assets
  - jekyll-feed
  - jekyll-maps
  - uglifier

jekyll_timeago:
  depth: 1
  today: 'Сегодня'
  yesterday: 'Вчера'
  tomorrow: 'Завтра'
  and: 'и'
  suffix: 'назад'
  prefix: ''
  suffix_future: ''
  prefix_future: 'in'
  years: 'года'
  year: 'год'
  months: 'мес.'
  month: 'мес.'
  weeks: 'нед.'
  week: 'нед.'
  days: 'дн.'
  day: 'дн.'

maps:
  google:
    api_key: AIzaSyCdzBPyxAeuk-0bG2pyMbO8d32PMBKgcRo

extlinks:
  attributes: {rel: nofollow, target: _blank} 
  rel_exclude: ['milkleaks.ru']
  
paginate: 8
paginate_path: "/page-:num/"

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
  
assets:
  destination: "/assets"
  compression: true
  caching:
    path: ".jekyll-cache/assets"
    type: file
    enabled: true
  sources:
    - "_assets/css"
    - "_assets/fonts"
    - "_assets/images"
    - "_assets/js"